<?xml version="1.0" encoding="UTF-8"?>
<testsuite tests="5" failures="2" skips="0">
     <testcase classname="test.TestProductionCode" name="test_FindFunction_WhichIsBroken_ShouldReturnZeroIfItemIsNotInList_WhichWorksEvenInOurBrokenCode"/>
     <testcase classname="test.TestProductionCode" name="test_FindFunction_WhichIsBroken_ShouldReturnTheIndexForItemsInList_WhichWillFailBecauseOurFunctionUnderTestIsBroken">
            <failure type="ASSERT FAILED">  Expected 1 Was 0 at line: 33 </failure>
     </testcase>
     <testcase classname="test.TestProductionCode" name="test_FunctionWhichReturnsLocalVariable_ShouldReturnTheCurrentCounterValue"/>
     <testcase classname="test.TestProductionCode" name="test_FunctionWhichReturnsLocalVariable_ShouldReturnTheCurrentCounterValueAgain"/>
     <testcase classname="test.TestProductionCode" name="test_FunctionWhichReturnsLocalVariable_ShouldReturnCurrentCounter_ButFailsBecauseThisTestIsActuallyFlawed">
            <failure type="ASSERT FAILED">  Expected 0x00001234 Was 0x00005A5A at line: 61 </failure>
     </testcase>
     <testcase classname="test.TestProduction2Code" name="test_Function2WhichReturnsLocalVariable_ShouldReturnCurrentCounter_ButFailsBecauseThisTestIsActuallyFlawed">
            <failure type="ASSERT FAILED">  Expected 0x00051234 Was 0xDEADBEEF at line: 47 </failure>
     </testcase>

</testsuite>
